#!/usr/bin/env Rscript

# ==============================================================================
# Script: 04_analysis/08_vegetated_area_proportions.R
#
# Project: Aridity and timescale bound the separability of vegetation water stress
#
# Purpose:
#   Same as summarise_global_area_proportions.R but the reference domain is
#   the vegetated land surface defined by mask C1:
#
#     C1: Et > 0 in at least one month (1981-2022)  AND  mean kNDVI > 0.025
#
#   C1 gives ~108.6 M km². The dual criterion requires both a detectable
#   greenness signal (mean kNDVI > 0.025, approx. NDVI > 0.20) and evidence
#   of active transpiration (GLEAM Et > 0).
#
#   Five mutually exclusive categories sum to 100% of the vegetated domain:
#
#     sig_pos      : significant positive   (significance code  2)
#     sig_neg      : significant negative   (significance code -2)
#     nosig_pos    : non-significant positive (significance code  1)
#     nosig_neg    : non-significant negative (significance code -1)
#     not_observed : within vegetated domain but no valid correlation this month
#
# Input:
#   Vegetated domain mask C1 (pre-computed TIF, run plot_vegetation_mask_c1.R first):
#     outputs/intermediate/vegetation_mask_c1.tif
#
#   NetCDF files with rho* Spearman correlations (one per indicator):
#     outputs/intermediate/absmax_spearman/abs_max_correlation_kndvi_<indicator>.nc
#
# Output:
#   outputs/tables/proportions_vegetated_area_all_months.csv
#
# Notes:
#   - Manuscript logic: both signs for Ep and ED; positive only for Et, SMrz, SMs.
#   - Spatial extent cropped to [-180, 180] longitude, [-65, 90] latitude.
#
# Dependencies:
#   terra, dplyr
#
# Repository location:
#   04_analysis/08_vegetated_area_proportions.R
# ==============================================================================

suppressPackageStartupMessages({
  library(terra)
  library(dplyr)
})

# ------------------------------------------------------------------------------
# User settings
# ------------------------------------------------------------------------------

config_file <- file.path("R", "config.R")
if (file.exists(config_file)) source(config_file)

dir_vi <- if (exists("paths") && !is.null(paths$absmax_spearman)) {
  paths$absmax_spearman
} else {
  file.path("outputs", "intermediate", "absmax_spearman")
}

veg_mask_file <- if (exists("paths") && !is.null(paths$veg_mask_c1)) {
  paths$veg_mask_c1
} else {
  file.path("outputs", "intermediate", "vegetation_mask_c1.tif")
}

out_csv <- if (exists("paths") && !is.null(paths$tables)) {
  file.path(paths$tables, "proportions_vegetated_area_all_months.csv")
} else {
  file.path("outputs", "tables", "proportions_vegetated_area_all_months.csv")
}

dir.create(dirname(out_csv), recursive = TRUE, showWarnings = FALSE)

variables    <- c("Ep", "Et", "ED", "SMrz", "SMs")
months_names <- c("January", "February", "March", "April", "May", "June",
                  "July", "August", "September", "October", "November", "December")

e_ll <- ext(-180, 180, -65, 90)

# ------------------------------------------------------------------------------
# Load vegetated domain mask C1 from pre-computed TIF
# (generated by plot_vegetation_mask_c1.R)
# ------------------------------------------------------------------------------

if (!file.exists(veg_mask_file)) {
  stop("Vegetated mask C1 not found: ", veg_mask_file,
       "\nRun plot_vegetation_mask_c1.R first.", call. = FALSE)
}

message("Loading vegetated domain mask (C1) from: ", veg_mask_file)

veg_domain <- rast(veg_mask_file)
veg_domain <- crop(veg_domain, e_ll)

cell_area  <- cellSize(veg_domain, unit = "km")
domain_km2 <- global(cell_area * veg_domain, "sum", na.rm = TRUE)$sum

message("Vegetated domain area (C1): ", round(domain_km2 / 1e6, 2), " million km²")

# ------------------------------------------------------------------------------
# Helper
# ------------------------------------------------------------------------------

get_area <- function(mask_r, cell_area) {
  global(cell_area * mask_r, "sum", na.rm = TRUE)$sum
}

# ------------------------------------------------------------------------------
# Main loop
# ------------------------------------------------------------------------------

message("Computing area proportions over vegetated domain (C1).")

results_list <- list()

for (v in variables) {
  message("Processing indicator: ", v)

  f_nc <- file.path(dir_vi, paste0("abs_max_correlation_kndvi_", v, ".nc"))
  if (!file.exists(f_nc)) stop("Input file not found: ", f_nc, call. = FALSE)

  nc        <- rast(f_nc)
  sig_stack <- nc[[grep("abs_max_significance", names(nc))]]

  if (nlyr(sig_stack) < 12) {
    stop("Expected 12 significance layers in ", f_nc, call. = FALSE)
  }

  for (m in 1:12) {
    sig <- crop(sig_stack[[m]], e_ll)
    sig[veg_domain == 0] <- NA

    sig_pos <- sig ==  2
    sig_neg <- sig == -2
    nos_pos <- sig ==  1
    nos_neg <- sig == -1

    a_sp <- get_area(sig_pos, cell_area)
    a_sn <- get_area(sig_neg, cell_area)
    a_np <- get_area(nos_pos, cell_area)
    a_nn <- get_area(nos_neg, cell_area)

    a_obs    <- a_sp + a_sn + a_np + a_nn
    a_notobs <- domain_km2 - a_obs

    # Manuscript logic: both signs for Ep and ED; positive only for Et, SMrz, SMs
    a_manuscript <- if (v %in% c("Ep", "ED")) a_sp + a_sn else a_sp

    results_list[[length(results_list) + 1]] <- data.frame(
      variable                     = v,
      month                        = months_names[m],
      month_id                     = m,
      domain_area_mill_km2         = round(domain_km2 / 1e6, 2),
      sig_pos                      = a_sp     / domain_km2,
      sig_neg                      = a_sn     / domain_km2,
      nosig_pos                    = a_np     / domain_km2,
      nosig_neg                    = a_nn     / domain_km2,
      not_observed                 = a_notobs / domain_km2,
      area_sig_pos_mill_km2        = round(a_sp / 1e6, 2),
      area_sig_neg_mill_km2        = round(a_sn / 1e6, 2),
      area_sig_tot_mill_km2        = round((a_sp + a_sn) / 1e6, 2),
      pct_sig_tot                  = round(100 * (a_sp + a_sn) / domain_km2, 1),
      area_sig_manuscript_mill_km2 = round(a_manuscript / 1e6, 2),
      pct_sig_manuscript           = round(100 * a_manuscript / domain_km2, 1)
    )

    message(
      "  ", months_names[m],
      ": observed = ", round(a_obs / 1e6, 1), " M km²",
      " | not observed = ", round(a_notobs / 1e6, 1), " M km²",
      " | sig+ = ", round(100 * a_sp / domain_km2, 1), "%",
      " | sig- = ", round(100 * a_sn / domain_km2, 1), "%"
    )
  }
}

# ------------------------------------------------------------------------------
# Save output
# ------------------------------------------------------------------------------

results_df <- bind_rows(results_list) |>
  arrange(variable, month_id)

write.csv(results_df, out_csv, row.names = FALSE)

message("Saved: ", out_csv)
